esphome:
  name: $hostname
  on_boot:
    priority: 600
    then:
      - output.turn_on: enable

esp8266:
  board: $board

logger:
  level: INFO
  logs:
    wifi: INFO
    mdns: INFO
    mqtt: INFO

wifi:
  fast_connect: true
  power_save_mode: HIGH
  output_power: 12db
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
globals:
  - id: on_minutes
    type: int
    restore_value: no
    initial_value: '0'
  - id: already_on
    type: int
    restore_value: no
    initial_value: '0'

### The valve will stay open for on_minutes
script:
  - id: run_watering
    then:
      - if:
          condition:
            lambda: 'return id(on_minutes) > 0;'
          then:
            - logger.log: "Watering!"
            - if:
                condition: 
                  lambda: 'return id(water_valve).position == COVER_CLOSED;'
                then:
                  - logger.log: "Opening watering valve"
                  - cover.open: water_valve
            - lambda: |-
                id(deep_sleep_1).set_sleep_duration(id(on_minutes)*60000);
            - mqtt.publish:
                topic: /${devicename}/watering/minutes
                retain: true
                payload: 0
            - logger.log: "Opened valve. Now sleeping until end"

          else:
            - if:
                condition:
                  lambda: 'return id(water_valve).position == COVER_OPEN;'
                then:
                  - logger.log: "No more watering. Closing valve"
                  - cover.close: water_valve
                  - lambda: |-
                      id(deep_sleep_1).set_sleep_duration(3600000); // 1h

mqtt:
  broker: $mqtt_server
    #username:
    #password: 
  topic_prefix: /${devicename}
  birth_message:
    #  topic: /${devicename}/status
    #  payload: online
  will_message:
    #  topic: /${devicename}/status
    #  payload: offline
  on_message:
    - topic: /${devicename}/watering/minutes
      then:
        - if:
            condition:
              lambda: "return id(already_on) == 0;"
            then:
              - lambda: |-
                  id(already_on) = 1;
                  id(on_minutes) = abs(stoi(x));
              - logger.log: 
                  format: "Watering command received. There are a total of %u minutes of watering."
                  args: [ 'id(on_minutes)' ]
              - script.execute: run_watering

    - topic: /${devicename}/esp/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
        - logger.log: "OTA mode active. The device will NOT sleep"
    - topic: /${devicename}/esp/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1
        - logger.log: "Sleep mode active, you can disable it now"

ota:

deep_sleep:
  id: deep_sleep_1
  run_duration: 500ms
  sleep_duration: 1h

web_server:
  port: 80

output:
  - platform: gpio
    pin: $valve_open_gpio
    id: valve_open
  - platform: gpio
    pin: $valve_close_gpio
    id: valve_close
  - platform: gpio
    pin: $enable_gpio
    id: enable

cover:
  - platform: template
    name: "Water Valve"
    id: water_valve
    assumed_state: true
    optimistic: true
    command_retain: true
    open_action:
      - output.turn_off: valve_close
      - output.turn_on: valve_open
      - delay: 250ms
      - output.turn_off: valve_open
      # Remove retained command message to avoid another execution at the next wakeup
      - mqtt.publish:
          topic: /${devicename}/cover/water_valve/command
          retain: true
          payload: 
    close_action:
      - output.turn_off: valve_open
      - output.turn_on: valve_close
      - delay: 63ms
      - output.turn_off: valve_close
      - globals.set: # if the valve was closed, stop keeping it open
          id: on_minutes
          value: '0'
      - mqtt.publish:
          topic: /${devicename}/cover/water_valve/command
          retain: true
          payload:
